# Generated by Django 4.0.1 on 2022-01-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='HP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='paliwo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='przebieg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
