# Generated by Django 4.0.1 on 2022-01-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_alter_produkt_hp_alter_produkt_paliwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='title',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='')),
                ('produkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.produkt')),
            ],
        ),
    ]
