# Generated by Django 4.0.1 on 2022-02-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0005_produkt_opis_alter_produkt_cena_alter_produkt_paliwo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marka',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Modelauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.marka')),
            ],
        ),
        migrations.RemoveField(
            model_name='marka',
            name='model',
        ),
        migrations.AlterField(
            model_name='produkt',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.modelauta'),
        ),
    ]
