# Generated by Django 4.0.1 on 2022-02-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0007_alter_marka_marka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelauta',
            old_name='model',
            new_name='model_samochodu',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='marka',
            new_name='model_samochodu',
        ),
    ]
